### ISSUE TITLE
Input html text in version 1.2.0

### ISSUE THREAD

**Issue by andreasluelsdorf** [conterra/mapapps-welcome#2]
### dn_welcome bundle
Even tough this issue is solved in version 1.3, I can't input formatted text into this bundle in the Live-Configuration.

I solved the problem by myself, using a "Eigener Inhalt" widget for input the textfile and after that I haved copied it in the Manuel-Configuration into the dn_welcome bunde /"infotext"

**Comment by matthiasstein** [comment]
The complete config cannot be started in version 1.2.0. I created a new issue for it: https://github.com/conterra/mapapps-welcome/issues/3

After fixing the problem locally, I can also use HTML code in the info text. I will make a new release.

**Comment by matthiasstein** [comment]
This is the new Release: https://github.com/conterra/mapapps-welcome/releases/tag/1.3.0
