### ISSUE TITLE
html-tags in info text are ignored

### ISSUE THREAD

**Issue by kbor-maschmi** [conterra/mapapps-welcome#4]
When using html-tags in the "infoText" these tags are ignored and displayed as text. (tested in mapapps 4.13.1, welcome 1.4.0/1.4.1-SNAPSHOT)

**Comment by sholtkamp** [comment]
Since version 1.4.0 of the welcome bundle, the v-html in the v-card-title containing the infoText has been replaced with a div.
This was done due to security concerns as v-html can be used for malicious purposes.

Therefore, HTML can no longer be used to define the infoText.
